import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../src/http/server.js';
import { FileRecordStore } from '../src/adapters/record-store.js';
import { PrivateImageStore } from '../src/adapters/image-store.js';

const jpeg = Buffer.from([0xff, 0xd8, 0xff, 0xd9]);
const metadata = { schemaVersion: 1, name: '一食堂', category: 'on-campus', location: '一食堂一楼', taste: '面条口感不错。', openingHours: '待补充', visitedAt: '2026-09-16', imageFilename: 'client-name.png' };
async function fixture(options = {}) {
  const root = await mkdtemp(join(tmpdir(), 'contributions-'));
  const repository = new FileRecordStore({ root });
  const app = createApp({ repository, storage: new PrivateImageStore({ root }), allowedOrigins: ['https://food.example.test'], reviewerTokens: ['reviewer-secret'], rateLimit: options.rateLimit || { windowMs: 60_000, max: 10 } });
  await new Promise((resolve) => app.listen(0, '127.0.0.1', resolve));
  return { root, repository, app, url: `http://127.0.0.1:${app.address().port}`, close: () => new Promise((resolve) => app.close(resolve)), cleanup: () => rm(root, { recursive: true, force: true }) };
}
function form(data = metadata, image = jpeg, type = 'image/jpeg') { const body = new FormData(); body.set('metadata', JSON.stringify(data)); body.set('image', new Blob([image], { type }), 'ignored.png'); return body; }

test('accepts a real JPEG, keeps it private, and returns only queue state', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(), headers: { Origin: 'https://food.example.test' } }); assert.equal(response.status, 202); const result = await response.json(); const stored = await ctx.repository.get(result.id); assert.equal(result.status, 'pending'); assert.match(stored.imageKey, /^images\/[0-9a-f-]+\.jpg$/); assert.equal(await readFile(join(ctx.root, stored.imageKey), 'hex'), jpeg.toString('hex')); assert.equal(response.headers.get('access-control-allow-origin'), 'https://food.example.test'); } finally { await ctx.close(); await ctx.cleanup(); } });
test('rejects declared MIME type that does not match file bytes', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(metadata, Buffer.from('not an image')) }); assert.equal(response.status, 422); assert.equal((await response.json()).error.code, 'invalid_image'); } finally { await ctx.close(); await ctx.cleanup(); } });
test('rejects an invalid calendar date', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form({ ...metadata, visitedAt: '2026-02-30' }) }); assert.equal(response.status, 422); } finally { await ctx.close(); await ctx.cleanup(); } });
test('enforces CORS origin and anonymous rate limit', async () => { const ctx = await fixture({ rateLimit: { windowMs: 60_000, max: 1 } }); try { const badOrigin = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(), headers: { Origin: 'https://other.example.test' } }); assert.equal(badOrigin.status, 403); const first = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); assert.equal(first.status, 202); const second = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); assert.equal(second.status, 429); } finally { await ctx.close(); await ctx.cleanup(); } });
test('requires reviewer authentication and records a rejection reason', async () => { const ctx = await fixture(); try { const submission = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); const { id } = await submission.json(); const unauthenticated = await fetch(`${ctx.url}/v1/admin/submissions`, { headers: { Authorization: 'Bearer wrong' } }); assert.equal(unauthenticated.status, 401); const missingReason = await fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject' }) }); assert.equal(missingReason.status, 422); const reviewed = await fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject', reason: '图片无法辨识。' }) }); assert.equal(reviewed.status, 200); assert.equal((await reviewed.json()).submission.status, 'rejected'); assert.equal((await ctx.repository.listAudits()).length, 1); } finally { await ctx.close(); await ctx.cleanup(); } });
test('requires a safe publication contract before approving a submission', async () => { const ctx = await fixture(); try { const submission = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); const { id } = await submission.json(); const review = (publicFields) => fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'approve', publicFields }) }); const unsafeId = await review({ id: '一食堂', imageApproved: false }); assert.equal(unsafeId.status, 422); const missingImageDecision = await review({ id: 'first-canteen' }); assert.equal(missingImageDecision.status, 422); const approved = await review({ id: 'first-canteen', imageApproved: false, updatedAt: null }); assert.equal(approved.status, 200); const result = await approved.json(); assert.deepEqual(result.submission.publicFields, { id: 'first-canteen', name: '一食堂', category: 'on-campus', location: '一食堂一楼', taste: '同学反馈：面条口感不错。', openingHours: null, visitedAt: '2026-09-16', updatedAt: null, price: '待补充。', imageApproved: false }); } finally { await ctx.close(); await ctx.cleanup(); } });

test('serves the moderation UI without embedding any reviewer token', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/admin/`); assert.equal(response.status, 200); assert.match(response.headers.get('content-type'), /text\/html/); const html = await response.text(); assert.match(html, /投稿审核台/); assert.match(html, /\/v1\/admin\/submissions/); assert.equal(html.includes('reviewer-secret'), false); assert.match(html, /textContent/, '投稿内容必须用 textContent 写入，避免注入'); assert.match(html, /function checkApproval/, '批准前必须在前端校验稳定标识与口感前缀'); assert.match(html, /function publicTaste/, '口感前缀不能重复叠加'); } finally { await ctx.close(); await ctx.cleanup(); } });

test('serves a pending image only to an authenticated reviewer', async () => { const ctx = await fixture(); try { const submission = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); const { id } = await submission.json(); const unauthorized = await fetch(`${ctx.url}/v1/admin/submissions/${id}/image`); assert.equal(unauthorized.status, 401); const authorized = await fetch(`${ctx.url}/v1/admin/submissions/${id}/image`, { headers: { Authorization: 'Bearer reviewer-secret' } }); assert.equal(authorized.status, 200); assert.equal(authorized.headers.get('content-type'), 'image/jpeg'); assert.equal(Buffer.from(await authorized.arrayBuffer()).toString('hex'), jpeg.toString('hex')); const missing = await fetch(`${ctx.url}/v1/admin/submissions/00000000-0000-0000-0000-000000000000/image`, { headers: { Authorization: 'Bearer reviewer-secret' } }); assert.equal(missing.status, 404); } finally { await ctx.close(); await ctx.cleanup(); } });

test('stores images under a server-generated key and refuses traversal keys', async () => { const root = await mkdtemp(join(tmpdir(), 'contributions-')); const storage = new PrivateImageStore({ root }); try { const key = await storage.put({ buffer: jpeg, extension: 'jpg' }); assert.match(key, /^images\/[0-9a-f-]+\.jpg$/); const stored = await storage.read(key); assert.equal(stored.buffer.toString('hex'), jpeg.toString('hex')); assert.equal(stored.contentType, 'image/jpeg'); await assert.rejects(() => storage.read('../outside.jpg'), (error) => error.status === 400 && error.code === 'invalid_storage_key'); } finally { await rm(root, { recursive: true, force: true }); } });

test('accepts the service own origin while rejecting other origins', async () => { const ctx = await fixture(); try { const sameOrigin = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(), headers: { Origin: ctx.url } }); assert.equal(sameOrigin.status, 202); const { id } = await sameOrigin.json(); const decision = await fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Origin: ctx.url, Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject', reason: '测试同源审核。' }) }); assert.equal(decision.status, 200); const crossOrigin = await fetch(`${ctx.url}/v1/admin/submissions`, { headers: { Origin: 'http://127.0.0.1:1' } }); assert.equal(crossOrigin.status, 403); } finally { await ctx.close(); await ctx.cleanup(); } });
