import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../src/http/server.js';
import { MemoryRepository } from '../src/adapters/repository.js';
import { LocalPrivateStorage } from '../src/adapters/storage.js';

const jpeg = Buffer.from([0xff, 0xd8, 0xff, 0xd9]);
const metadata = { schemaVersion: 1, name: '一食堂', category: 'on-campus', location: '一食堂一楼', taste: '面条口感不错。', openingHours: '待补充', visitedAt: '2026-09-16', imageFilename: 'client-name.png' };
async function fixture(options = {}) { const root = await mkdtemp(join(tmpdir(), 'contributions-')); const repository = new MemoryRepository(); const app = createApp({ repository, storage: new LocalPrivateStorage(root), allowedOrigins: ['https://food.example.test'], reviewerTokens: ['reviewer-secret'], rateLimit: options.rateLimit || { windowMs: 60_000, max: 10 } }); await new Promise((resolve) => app.listen(0, '127.0.0.1', resolve)); return { root, repository, app, url: `http://127.0.0.1:${app.address().port}`, close: () => new Promise((resolve) => app.close(resolve)) }; }
function form(data = metadata, image = jpeg, type = 'image/jpeg') { const body = new FormData(); body.set('metadata', JSON.stringify(data)); body.set('image', new Blob([image], { type }), 'ignored.png'); return body; }

test('accepts a real JPEG, keeps it private, and returns only queue state', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(), headers: { Origin: 'https://food.example.test' } }); assert.equal(response.status, 202); const result = await response.json(); const stored = await ctx.repository.get(result.id); assert.equal(result.status, 'pending'); assert.match(stored.imageKey, /^pending\/[0-9a-f-]+\.jpg$/); assert.equal(await readFile(join(ctx.root, stored.imageKey), 'hex'), jpeg.toString('hex')); assert.equal(response.headers.get('access-control-allow-origin'), 'https://food.example.test'); } finally { await ctx.close(); } });
test('rejects declared MIME type that does not match file bytes', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(metadata, Buffer.from('not an image')) }); assert.equal(response.status, 422); assert.equal((await response.json()).error.code, 'invalid_image'); } finally { await ctx.close(); } });
test('rejects an invalid calendar date', async () => { const ctx = await fixture(); try { const response = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form({ ...metadata, visitedAt: '2026-02-30' }) }); assert.equal(response.status, 422); } finally { await ctx.close(); } });
test('enforces CORS origin and anonymous rate limit', async () => { const ctx = await fixture({ rateLimit: { windowMs: 60_000, max: 1 } }); try { const badOrigin = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form(), headers: { Origin: 'https://other.example.test' } }); assert.equal(badOrigin.status, 403); const first = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); assert.equal(first.status, 202); const second = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); assert.equal(second.status, 429); } finally { await ctx.close(); } });
test('requires reviewer authentication and records a rejection reason', async () => { const ctx = await fixture(); try { const submission = await fetch(`${ctx.url}/v1/submissions`, { method: 'POST', body: form() }); const { id } = await submission.json(); const unauthenticated = await fetch(`${ctx.url}/v1/admin/submissions`, { headers: { Authorization: 'Bearer wrong' } }); assert.equal(unauthenticated.status, 401); const missingReason = await fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject' }) }); assert.equal(missingReason.status, 422); const reviewed = await fetch(`${ctx.url}/v1/admin/submissions/${id}/review`, { method: 'POST', headers: { Authorization: 'Bearer reviewer-secret', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject', reason: '图片无法辨识。' }) }); assert.equal(reviewed.status, 200); assert.equal((await reviewed.json()).submission.status, 'rejected'); assert.equal(ctx.repository.audits.length, 1); } finally { await ctx.close(); } });
