import { Pool } from 'pg';
import { HttpError } from '../errors.js';
import { publicRecord } from './repository.js';

export class PostgresRepository {
  constructor(connectionString) { this.pool = new Pool({ connectionString }); }
  async migrate() { await this.pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE TABLE IF NOT EXISTS submissions (id uuid PRIMARY KEY, metadata jsonb NOT NULL, image_key text NOT NULL UNIQUE, status text NOT NULL CHECK (status IN ('pending','approved','rejected')), public_fields jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL); CREATE TABLE IF NOT EXISTS moderation_audits (id uuid PRIMARY KEY, submission_id uuid NOT NULL REFERENCES submissions(id), action text NOT NULL, reviewer text NOT NULL, reason text, created_at timestamptz NOT NULL);`); }
  async create(metadata, imageKey) { const result = await this.pool.query(`INSERT INTO submissions (id, metadata, image_key, status, created_at, updated_at) VALUES (gen_random_uuid(), $1, $2, 'pending', now(), now()) RETURNING *`, [metadata, imageKey]); return row(result.rows[0]); }
  async list(status) { const result = await this.pool.query(`SELECT * FROM submissions WHERE ($1::text IS NULL OR status = $1) ORDER BY created_at ASC`, [status || null]); return result.rows.map((item) => publicRecord(row(item))); }
  async get(id) { const result = await this.pool.query('SELECT * FROM submissions WHERE id = $1', [id]); if (!result.rowCount) throw new HttpError(404, 'not_found', '投稿不存在。'); return row(result.rows[0]); }
  async review(id, action, reviewer, reason, publicFields) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const existing = await client.query('SELECT * FROM submissions WHERE id = $1 FOR UPDATE', [id]); if (!existing.rowCount) throw new HttpError(404, 'not_found', '投稿不存在。'); if (existing.rows[0].status !== 'pending') throw new HttpError(409, 'invalid_state', '该投稿已审核。'); if (!['approve', 'reject'].includes(action)) throw new HttpError(422, 'invalid_action', 'action 必须为 approve 或 reject。'); if (action === 'reject' && !reason?.trim()) throw new HttpError(422, 'missing_rejection_reason', '拒绝投稿时必须填写原因。'); const updated = await client.query(`UPDATE submissions SET status = $2, public_fields = $3, updated_at = now() WHERE id = $1 RETURNING *`, [id, action === 'approve' ? 'approved' : 'rejected', publicFields || null]); await client.query(`INSERT INTO moderation_audits (id, submission_id, action, reviewer, reason, created_at) VALUES (gen_random_uuid(), $1, $2, $3, $4, now())`, [id, action, reviewer, reason?.trim() || null]); await client.query('COMMIT'); return row(updated.rows[0]); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async close() { await this.pool.end(); }
}

function row(value) { return { id: value.id, metadata: value.metadata, imageKey: value.image_key, status: value.status, publicFields: value.public_fields, createdAt: value.created_at.toISOString(), updatedAt: value.updated_at.toISOString() }; }
